
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package lexicalanalyzer.go;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int DOUBLE_INTERROGATION = 76;
  public static final int IDENTIFIER = 83;
  public static final int BLANK_IDENTIFIER = 82;
  public static final int ANDEQ = 46;
  public static final int TYPE = 16;
  public static final int CHANNEL = 35;
  public static final int GO = 2;
  public static final int CONST = 10;
  public static final int INT_LITERAL = 77;
  public static final int NOTEQ = 33;
  public static final int PLUSEQ = 40;
  public static final int FUNC = 21;
  public static final int RBRACK = 71;
  public static final int DEFER = 13;
  public static final int COMMA = 63;
  public static final int RBRACE = 73;
  public static final int ANDNOTEQ = 61;
  public static final int RPAREN = 69;
  public static final int LBRACK = 70;
  public static final int ANDAND = 57;
  public static final int OROR = 34;
  public static final int LBRACE = 72;
  public static final int STRUCT = 4;
  public static final int LPAREN = 68;
  public static final int XOREQ = 84;
  public static final int FALSE = 6;
  public static final int NOT = 30;
  public static final int VAR = 20;
  public static final int GOTO = 17;
  public static final int RUNE_LITERAL = 80;
  public static final int PACKAGE = 23;
  public static final int MOD = 29;
  public static final int SELECT = 9;
  public static final int FALLTHROUGH = 11;
  public static final int IMG_LITERAL = 79;
  public static final int TRUE = 5;
  public static final int PLUS = 49;
  public static final int EQUAL = 37;
  public static final int INTERFACE = 22;
  public static final int CHAN = 26;
  public static final int SWITCH = 24;
  public static final int FOR = 28;
  public static final int RSHIFTEQ = 55;
  public static final int GREATER = 43;
  public static final int DIV = 48;
  public static final int RETURN = 19;
  public static final int MULT = 41;
  public static final int ANDNOT = 54;
  public static final int ELSE = 27;
  public static final int BREAK = 7;
  public static final int GTEQ = 44;
  public static final int INTERROGATION = 74;
  public static final int DOT = 66;
  public static final int MAP = 3;
  public static final int STRING_LITERAL = 81;
  public static final int EQEQ = 62;
  public static final int EOF = 0;
  public static final int SEMICOLON = 64;
  public static final int DEFAULT = 8;
  public static final int MULTEQ = 59;
  public static final int IMPORT = 18;
  public static final int MINUS = 31;
  public static final int FLOAT_LITERAL = 78;
  public static final int LTEQ = 45;
  public static final int CHANNELEQ = 38;
  public static final int OR = 32;
  public static final int error = 1;
  public static final int SUSPOINTS = 65;
  public static final int DIVEQ = 60;
  public static final int LSHIFTEQ = 36;
  public static final int CONTINUE = 25;
  public static final int IF = 14;
  public static final int MINUSMINUS = 53;
  public static final int COLON = 67;
  public static final int OREQ = 58;
  public static final int CASE = 12;
  public static final int PLUSPLUS = 51;
  public static final int RSHIFT = 52;
  public static final int RANGE = 15;
  public static final int LESS = 39;
  public static final int AND = 56;
  public static final int LSHIFT = 50;
  public static final int XOR = 42;
  public static final int HASH = 75;
  public static final int MINUSEQ = 47;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GO",
  "MAP",
  "STRUCT",
  "TRUE",
  "FALSE",
  "BREAK",
  "DEFAULT",
  "SELECT",
  "CONST",
  "FALLTHROUGH",
  "CASE",
  "DEFER",
  "IF",
  "RANGE",
  "TYPE",
  "GOTO",
  "IMPORT",
  "RETURN",
  "VAR",
  "FUNC",
  "INTERFACE",
  "PACKAGE",
  "SWITCH",
  "CONTINUE",
  "CHAN",
  "ELSE",
  "FOR",
  "MOD",
  "NOT",
  "MINUS",
  "OR",
  "NOTEQ",
  "OROR",
  "CHANNEL",
  "LSHIFTEQ",
  "EQUAL",
  "CHANNELEQ",
  "LESS",
  "PLUSEQ",
  "MULT",
  "XOR",
  "GREATER",
  "GTEQ",
  "LTEQ",
  "ANDEQ",
  "MINUSEQ",
  "DIV",
  "PLUS",
  "LSHIFT",
  "PLUSPLUS",
  "RSHIFT",
  "MINUSMINUS",
  "ANDNOT",
  "RSHIFTEQ",
  "AND",
  "ANDAND",
  "OREQ",
  "MULTEQ",
  "DIVEQ",
  "ANDNOTEQ",
  "EQEQ",
  "COMMA",
  "SEMICOLON",
  "SUSPOINTS",
  "DOT",
  "COLON",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "INTERROGATION",
  "HASH",
  "DOUBLE_INTERROGATION",
  "INT_LITERAL",
  "FLOAT_LITERAL",
  "IMG_LITERAL",
  "RUNE_LITERAL",
  "STRING_LITERAL",
  "BLANK_IDENTIFIER",
  "IDENTIFIER",
  "XOREQ"
  };
}

