
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 18 02:19:42 BRT 2018
//----------------------------------------------------

package lexicalanalyzer.go;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int BOOL = 27;
  public static final int ANDEQ = 84;
  public static final int CHANNEL = 98;
  public static final int TYPE = 25;
  public static final int GO = 13;
  public static final int FLOAT32 = 42;
  public static final int CONST = 5;
  public static final int NOTEQ = 65;
  public static final int INT32 = 32;
  public static final int UINTPTR = 39;
  public static final int PLUSEQ = 80;
  public static final int FUNC = 12;
  public static final int RBRACK = 53;
  public static final int DEFER = 8;
  public static final int COMMA = 55;
  public static final int RBRACE = 51;
  public static final int ANDNOTEQ = 104;
  public static final int RPAREN = 49;
  public static final int LBRACK = 52;
  public static final int ANDAND = 66;
  public static final int NUMERO = 91;
  public static final int OROR = 67;
  public static final int STRUCT = 23;
  public static final int LBRACE = 50;
  public static final int DECEQ = 99;
  public static final int LPAREN = 48;
  public static final int XOREQ = 86;
  public static final int INTEGER_LITERAL = 94;
  public static final int FALSE = 47;
  public static final int NOT = 61;
  public static final int COMENTARIO = 92;
  public static final int VAR = 26;
  public static final int GOTO = 14;
  public static final int UINT32 = 37;
  public static final int PACKAGE = 19;
  public static final int COMPLEX128 = 45;
  public static final int MOD = 77;
  public static final int INT16 = 31;
  public static final int SELECT = 22;
  public static final int FALLTHROUGH = 10;
  public static final int RUNE = 41;
  public static final int TRUE = 46;
  public static final int PLUS = 70;
  public static final int QUOTE = 101;
  public static final int OCTAL_LITERAL = 97;
  public static final int EQUAL = 58;
  public static final int UINT8 = 35;
  public static final int INTERFACE = 17;
  public static final int INT8 = 30;
  public static final int CHAN = 4;
  public static final int SWITCH = 24;
  public static final int FOR = 11;
  public static final int RSHIFTEQ = 89;
  public static final int GREATER = 59;
  public static final int DIV = 73;
  public static final int MULT = 72;
  public static final int FLOAT64 = 43;
  public static final int RETURN = 21;
  public static final int IMAGINARY_LITERAL = 105;
  public static final int ANDNOT = 103;
  public static final int ELSE = 9;
  public static final int BREAK = 2;
  public static final int GTEQ = 64;
  public static final int DOT = 56;
  public static final int INT = 29;
  public static final int INT64 = 33;
  public static final int MAP = 18;
  public static final int HEXAL_LITERAL = 96;
  public static final int STRING_LITERAL = 93;
  public static final int EQEQ = 62;
  public static final int UINT16 = 36;
  public static final int EOF = 0;
  public static final int SEMICOLON = 54;
  public static final int DEFAULT = 7;
  public static final int UNDERSCORE = 100;
  public static final int MULTEQ = 82;
  public static final int IMPORT = 16;
  public static final int MINUS = 71;
  public static final int COMPLEX64 = 44;
  public static final int FLOAT_LITERAL = 95;
  public static final int LTEQ = 63;
  public static final int OR = 75;
  public static final int error = 1;
  public static final int SUSPOINTS = 102;
  public static final int DIVEQ = 83;
  public static final int LSHIFTEQ = 88;
  public static final int CONTINUE = 6;
  public static final int IF = 15;
  public static final int ID = 90;
  public static final int MODEQ = 87;
  public static final int MINUSMINUS = 69;
  public static final int COLON = 57;
  public static final int UINT = 34;
  public static final int UINT64 = 38;
  public static final int ALL_STRINGS_LITERAL = 106;
  public static final int OREQ = 85;
  public static final int CASE = 3;
  public static final int PLUSPLUS = 68;
  public static final int RSHIFT = 79;
  public static final int STRING = 28;
  public static final int RANGE = 20;
  public static final int LESS = 60;
  public static final int BYTE = 40;
  public static final int AND = 74;
  public static final int LSHIFT = 78;
  public static final int XOR = 76;
  public static final int MINUSEQ = 81;
}

